---
pgrs_version: 11
pgrs_archive_dir: /var/lib/postgresql/{{ pgrs_version }}/archive
pgrs_data_dir:   /var/lib/postgresql/{{ pgrs_version }}/main
pgrs_bin_dir:    /usr/lib/postgresql/{{ pgrs_version }}/bin
pgrs_config_dir: /etc/postgresql/{{ pgrs_version }}/main
pgrs_config: "{{ pgrs_config_dir }}/postgresql.conf"
pgrs_service: postgresql
pgrs_user:
  type: host
  name: replication
  database: replication
  address: 0.0.0.0/0
  method: md5
  password: toor
pgrs_pg_settings:
  listen_addresses: "*"
  wal_level: hot_standby
  synchronous_commit: true
  archive_mode: true
  archive_command: cp %p {{ pgrs_archive_dir }}/%f
  max_wal_senders: 5
  wal_keep_segments: 32
  hot_standby: true
  wal_sender_timeout: 5000
  wal_receiver_status_interval: 2
  max_standby_streaming_delay: -1
  max_standby_archive_delay: -1
  restart_after_crash: false
  hot_standby_feedback: true
pgrs_recovery_settings:
  standby_mode: true
  primary_conninfo: >-
    host={{ pgrs_master }}
    user={{ pgrs_user.name }}
    application_name={{ pgrs_slave }}-slave
pgrs_hba_defaults:
  - type: local
    name: all
    database: all
    method: trust
  - type: host
    name: all
    database: all
    address: 127.0.0.1/32
    method: trust
  - type: host
    name: all
    database: all
    address: ::1/128
    method: trust
  - type: host
    name: app
    database: app
    address: 0.0.0.0/0
    method: md5
pgrs_slave_script: /usr/local/bin/pg_slave_init.sh
pgrs_slave_config: /etc/pg_slave_init.conf
pgrs_pgpass_hosts:
  - "{{ pgrs_slave }}"
  - "{{ pgrs_master }}"
pgrs_replica_set_master: "{{ pgrs_master }}"
